- name: create Jenkins jobs
  hosts: localhost
  connection: local
  tasks:
  - name: Create a jenkins job using basic authentication
    community.general.jenkins_job:
      config: "{{ lookup('file', 'test.xml') }}"
      name: test-job
      password: admin123
      url: http://172.31.16.117:8080
      user: admin