- name: Single branch Pipeline
  ansible.builtin.include_tasks:
    file: sjob.yml
  loop: "{{sjobs}}"

- name: Multibranch Pipeline
  ansible.builtin.include_tasks:
    file: mjob.yml
  loop: "{{mjobs}}"