- name: check if the job is exist or not
  community.general.jenkins_job_info:
    name: "{{item.job_name}}"
    user: admin
    password: admin123
    url: http://172.31.87.248:8080
  register: jenkins_job_status
  ignore_errors: true


- name: copy Xml file
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/test.xml
  when: jenkins_job_status.failed

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.87.248:8080
    user: admin
  when: jenkins_job_status.failed
