sjobs:
  - { get_repo_url: https://github.com/jayadeep2702/roboshopp-terraform.git, job_name: roboshop-terraform}
  - { get_repo_url: https://github.com/jayadeep2702/roboshopp-ansible.git, job_name: roboshop-ansible}
  - { get_repo_url: https://github.com/jayadeep2702/aws-ssm-parameter-store.git, job_name: aws-ssm-parameter-store}



mjobs:
  - { get_repo_url: https://github.com/jayadeep2702/cart.git, job_name: cart}
  -  { get_repo_url: https://github.com/jayadeep2702/catalogue.git, job_name: catalogue}
  - { get_repo_url: https://github.com/jayadeep2702/user.git, job_name: user}
  - { get_repo_url: https://github.com/jayadeep2702/shipping.git, job_name: shipping}
  - { get_repo_url: https://github.com/jayadeep2702/payment.git, job_name: payment}
  -  { get_repo_url: https://github.com/jayadeep2702/dispatch.git, job_name: dispatch}
  -  { get_repo_url: https://github.com/jayadeep2702/frontend.git, job_name: frontend}

